### PR TITLE
Add publishing stuff

### PR DESCRIPTION
**Pull request by kalbermattenm**
This add publishing stuff (but only for a Windows environment)

### CODE REVIEW

**Comment by rbovard** [comment]
Cool, thanks a lot. I'll test that on next changes :)

**Comment by rbovard** [comment]
Just tested and it worked fine, see https://github.com/geomapfish/geomapfish.github.io/commit/49156b20c3cb86a1b7d65316127090194c96ba28

Just a question: why did you set `DELETE_OUTPUT_DIRECTORY = False` and remove it manually in the batch? Because in my case, I got this warning:

```
Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.
```

**Comment by kalbermattenm** [comment]
Hmmmm... I cannot remember, but I think this was mainly a debug issue.

For me it would really make sense to set it to `True` ?

**Comment by rbovard** [comment]
I think you deleted it manually to *clean* the git stuff before publish it with `publishconf.py`. And you needed to keep this folder in publish process to keep those git stuff... Am I right?

So it's good like that.

**Pull request merged**
