### PR TITLE
Add documentation links

### LINKED ISSUE #66: Add documentation link
It would be great to have a direct access to the documentation

**from** https://geomapfish.org 

**to** https://camptocamp.github.io/c2cgeoportal/master/ 

image

I did not find where to propose this.

### PR DESCRIPTION
**Pull request by rbovard**
Fix #66

As discussed at last meeting.

@pfanguin @remyguillaume Please take a look here: https://www.cartoriviera.ch/web/gmf/documentation

Maybe we can also reorder top links in the same time, what do you think?

I'll do the french and german pages after your first comments.

### CODE REVIEW

**Comment by pfanguin** [comment]
@rbovard : thanks for the job ! For me it's ok ! 
For the order of top links, you think by alphabetical order ?

**Comment by rbovard** [comment]
Thanks for the feedback.

No, I was a more thinking about logical or importance (features could be more "important" than community).

**Comment by pfanguin** [comment]
Ok for me it could be great to have this order : 
home, functionalities, documentation, gallery, community, roadmap

**Comment by rbovard** [comment]
Demo link updated.

Please review.

**Comment by pfanguin** [comment]
It's ok for me ! Thanks

**Comment by svareg** [comment]
Hello @rbovard,

Sorry, I didn't see you message.
Actually @remyguillaume is my private account, I don't use it really often. 
Could you next time notice me at @svareg ? This is my BS account. Thanks!

And thank you for those changes in the website, this looks good ! :)

**Pull request merged**
