### PR TITLE
Use new theme

### PR DESCRIPTION
**Pull request by rbovard**
Usage of the theme [pelican-bootstrap3](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3) instead of default one.

You can see the demo here: https://map.nyon.ch/sitnyon/gmf/

Notes:
* No customization was done (only the install)
* This theme can be translated but there is only the german for now (english is the default)

@kalbermattenm What do you think of this theme?

### CODE REVIEW

**Comment by kalbermattenm** [comment]
Cool ! It is responsive !

Do you think that you will have any time to maybe just add the GMF logo until Monday ?

I would like to make a demo at the GMF User group (and I will not have any time to do something until then...)

**Comment by rbovard** [comment]
Logo and favicon added, demo updated.

**Comment by rbovard** [comment]
I noticed that the `PAGE_ORDER_BY` seems not to be taken in account in this theme, so the menu is sorted by title and not by file name.

**Comment by kalbermattenm** [comment]
> I noticed that the PAGE_ORDER_BY seems not to be taken in account in this theme, so the menu is sorted by title and not by file name.

Oh... OK... I am sure that there is a way to fix that...

Thanks a lot for the logo update

Please merge

**Pull request merged**
