### PR TITLE
[WIP] Ajout de Belmont-sur Lausanne

### PR DESCRIPTION
**Pull request by ponceta**

### CODE REVIEW

**Comment by rbovard** [comment]
Thanks for your input!

This raises a question, are all communes of an entity (like SIGIP, Cartoriviera, CJL) member of the UG or only the entity?

My opinion is that in your case, we should mention SIGIP and not Pully and Belmont.

Any thought @kalbermattenm @gnerred?

*We also need to handle the case with CJL and Morges...*

**Comment by kalbermattenm** [comment]
It's up to these communities to answer....

**Comment by rbovard** [comment]
Okay, I opened a separate issue to discuss it https://github.com/geomapfish/geomapfish_website/issues/53

**Comment by kalbermattenm** [comment]
As shown by the discussion, I think that it would make sense not to list every member of each organization of each GMF partner.

Except this remark, @ponceta could you add lines to the list in alphabetical order, as @rbovard did ?

**Comment by rbovard** [comment]
ping @ponceta

**Comment by ponceta** [comment]
I think Belmont-sur-Lausanne is not a member of the user-group but a contributor.

**Comment by rbovard** [comment]
Ok, thanks for your feedback.

BTW, could you please also take a look to #53?

**Pull request closed without merging**
