### PR TITLE
Refactor GMF website

### PR DESCRIPTION
**Pull request by kalbermattenm**
This is quite a refactoring. I still have to apply the German corrections (thanks @voisardf)

There is a demo here:

https://sitn.ne.ch/web/gmf/

@rbovard, could you please review this PR.

@gnerred, could have a look at the demo and tell me if this looks good (or not...) ?

@luisteba, ok for you ?

### CODE REVIEW

**Comment by kalbermattenm** [comment]
ping @ebelo, @ybolognini, is it OK for you as well ?

**Comment by gnerred** [comment]
Thanks for the job ! It looks good to me.

**Comment by ybolognini** [comment]
Looks good, thanks

**Comment by luisteba** [comment]
Merci beaucoup! Beau travail.
Toutefois, je proposerai d'accéder à la page "Meeting" de façon plus sécurisée.
L'accès à cette page, fait partie des avantages d'un membre GMF, je trouve.
Qu'en penses-tu?

**Comment by kalbermattenm** [comment]
Je peux supprimer le lien direct. La page, quant à elle, restera toujours visible, car le site est directement hébergé sur Github.

Est-ce OK pour toi ?

**Comment by luisteba** [comment]
OK pour moi, merci.

**Review by rbovard — COMMENTED** [review]
Thanks a lot for the work @kalbermattenm! It looks very good to me.

Here are some complements:

* Maybe we can close this issue https://github.com/geomapfish/geomapfish_website/issues/28 with this PR or do you see something else to add?
* Since the 2.3 is now out, it could be the occasion to also update Gallery and Roadmap?
* About https://github.com/geomapfish/geomapfish_website/issues/36, we can simply add a link in the bottom of the functionalities page to redirect to https://github.com/camptocamp/ngeo/blob/master/docs/features.md? What do you think?

For the two last points, I can update the PR if you want.

**Comment by kalbermattenm** [comment]
> * Maybe we can close this issue #28 with this PR or do you see something else to add?

Nope, nothing to add, I will close #28 once this PR is merged.

> * Since the 2.3 is now out, it could be the occasion to also update Gallery and Roadmap?

Yes, I will update these two, thanks for the reminder.

> * About #36, we can simply add a link in the bottom of the functionalities page to redirect to https://github.com/camptocamp/ngeo/blob/master/docs/features.md? What do you think?

Oh, that's bright. I can take care of it, don't worry

Thanks a lot for the review !

**Comment by kalbermattenm** [comment]
Merging !

Thanks to everybody !

**Pull request merged**
