### PR TITLE
Get meetings minutes from old website

### LINKED ISSUE #27: Get PVs from old site
Hidden pages linked in community page

### PR DESCRIPTION
**Pull request by rbovard**
Fix #27

Demo: https://map.nyon.ch/gmf/community

@kalbermattenm I let you check the structure and the style. After that I'll import the old ones.

### CODE REVIEW

**Comment by kalbermattenm** [comment]
Looks really good to me !

Thanks a lot for all that work. I will not be able to help on this one before a while. I currently spending my time on another project which is quite time consuming... sorry...

**Comment by rbovard** [comment]
Thanks! No worries about that :)

**Comment by rbovard** [comment]
I finally imported all old pages, including attached files (for the linked documents, I did nothing expect copied the link).

@kalbermattenm Please take a global look, I did a lot of "copy paste" with Notepadd++/Excel

When you're ok for merging, you can remove the old pages on the old site (or even remove it, with a redirection to the new one?)

**Review by kalbermattenm — APPROVED** [review]
Whow ! Nice work, thanks a lot @rbovard !

Although I have not read everything, LGTM

**Pull request merged**
