### PR TITLE
Add Meeting Minutes + Changes to the Roadmap

### PR DESCRIPTION
**Pull request by svareg**

### CODE REVIEW

**Comment by pfanguin** [comment]
@svareg : Thanks for the job, it looks good for me !

**Review by rbovard — APPROVED** [review]
LGTM, please merge.

@pfanguin Could you please deploy?

**Comment by svareg** [comment]
Merge is done.
@pfanguin @rbovard  Could one of you deploy it please ?
Thanks !

**Comment by rbovard** [comment]
It's done:
- https://geomapfish.org/fr/meeting_minutes/2021-06-08
- https://geomapfish.org/de/meeting_minutes/2021-06-08

**Pull request merged**
